# Generated by Django 5.1.5 on 2025-01-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_id',
            new_name='table',
        ),
    ]
